# Generated by Django 6.0.3 on 2026-03-05 19:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Identificador único da sessão de conversa', unique=True, verbose_name='ID da Sessão')),
                ('iniciada_em', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Última atividade')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-atualizada_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('humano', 'Humano'), ('assistente', 'Assistente')], help_text='Quem enviou esta mensagem: humano ou assistente', max_length=15, verbose_name='Tipo')),
                ('conteudo', models.TextField(help_text='Texto da mensagem', verbose_name='Conteúdo')),
                ('tokens_usados', models.IntegerField(default=0, verbose_name='Tokens usados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chatbot.conversa', verbose_name='Conversa')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['criado_em'],
            },
        ),
    ]
